name: 'GAWG Notify action'
description: 'This action sends a notification containing workflow info to the desired channel.'
author: Álvaro García Pizarro
branding:
  icon: 'inbox'
  color: 'gray-dark'

inputs:
  messaging_app:
    type: string
    description: 'Messaging app to send the notification to.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate Workflow Summary Report
      shell: bash
      run: |
        summary=$(cat $GITHUB_STEP_SUMMARY)
        echo "Summary content:"
        echo "$summary"
        
    - name: No notification needed
      if: ${{ inputs.messaging_app == 'none' }}
      shell: bash
      run: |
        echo "No notification needed. Skipping this job."  

    - name: Email notification
      if: ${{ inputs.messaging_app == 'email' }}
      shell: bash
      run: |
        echo "Sending email notification to the team."

    - name: Slack notification
      if: ${{ inputs.messaging_app == 'slack' }}
      shell: bash
      run: |
        echo "Sending Slack notification to the team."

    - name: Microsoft Teams notification
      if: ${{ inputs.messaging_app == 'msteams' }}
      shell: bash
      run: |
        echo "Sending Microsoft Teams notification to the team."